// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iprehyjvxdvxqyofmovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcmVoeWp2eGR2eHF5b2Ztb3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjUwNjksImV4cCI6MjA2NzMwMTA2OX0.KUiDiqrMN7gah_pZBfxRaDam5yhgqi5m0yQBhgm-CGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});